"""Initial Migration

Revision ID: 63b1464f6dc4
Revises: 
Create Date: 2023-04-11 18:24:54.160573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63b1464f6dc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_id', table_name='transaction')
    op.drop_table('transaction')
    op.drop_index('ix_user_company_id', table_name='user')
    op.drop_index('ix_user_company_name', table_name='user')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_id', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_customer_id', table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('customer_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dob', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('number_of_transactions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transaction_dates', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('transactions_per_week', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transactions_time_frame', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('types_of_merchants', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='customer_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_customer_id', 'customer', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company_category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.create_index('ix_user_company_name', 'user', ['company_name'], unique=False)
    op.create_index('ix_user_company_id', 'user', ['company_id'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date_and_time', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('cc_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('merchant', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('merchant_category', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('street', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('zip', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('city_population', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transaction_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('unix_time', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('merchant_latitude', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('merchant_longitude', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_fraud', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='transaction_customer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='transaction_pkey')
    )
    op.create_index('ix_transaction_id', 'transaction', ['id'], unique=False)
    # ### end Alembic commands ###
